default_settings: null
behaviors:
  Tralalelo:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 81920
      learning_rate: 0.003
      beta: 0.005
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 5000000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 2
    even_checkpoints: true
    max_steps: 10000000
    time_horizon: 200
    summary_freq: 100000
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: X:\Unity\Room_AI_URP\TralaleloEnv\A.L.F - AI Life Form Wallpaper.exe
  env_args: null
  base_port: 5015
  num_envs: 3
  num_areas: 1
  timeout_wait: 60
  seed: 42
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
  no_graphics_monitor: false
environment_parameters: null
checkpoint_settings:
  run_id: Tralalelo_09_pass_targetReward
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
